kind: pipeline
name: publish to docker hub

steps:
- name: flake8
  image: alpine/flake8:3.7.9
  commands:
  - flake8

- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-search
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    branch:
      exclude:
      - dependabot/**

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-search
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: test

depends_on:
- publish to docker hub

services:
- name: search-pg
  image: postgres:9.6
  volumes:
  - name: search-pg-v
    path: /var/lib/postgresql/data
  environment:
    POSTGRES_USER: search
    POSTGRES_DATABASE: search
    POSTGRES_PASSWORD: search

- name: search-es
  image: docker.elastic.co/elasticsearch/elasticsearch:6.8.3
  volumes:
  - name: search-es-v-data
    path: /usr/share/elasticsearch/data
  - name: search-es-v-snapshot
    path: /opt/hoover/es-snapshots
  environment:
    discovery.type: single-node
    path.repo: /opt/hoover/es-snapshots


steps:
- name: run tests
  image: liquidinvestigations/hoover-search:${DRONE_COMMIT_BRANCH}
  environment:
    HOOVER_DB: postgresql://search:search@search-pg:5432/search
    WAIT_HOSTS: search-es:9200, search-pg:5432
    WAIT_HOSTS_TIMEOUT: 60
    DJANGO_SETTINGS_MODULE: testsuite.settings
    SECRET_KEY: secret-key-for-testing
  commands:
  - sleep 20
  - cd /opt/hoover/search
  - py.test -vv
  trigger:
    events:
    - push

volumes:
- name: search-pg-v
  temp: {}
- name: search-es-v-data
  temp: {}
- name: search-es-v-snapshot
  temp: {}
---

kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
