kind: pipeline
name: test

steps:
- name: flake8
  image: python:3.7-stretch
  commands:
  - pip install flake8 > /dev/null
  - echo 'not running flake8 yet'

- name: docker build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - until docker version; do sleep 3; done
  - docker build . --tag hoover-search-testing

- name: docker setup
  image: docker/compose:1.24.0
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - apk add git
  - git clone https://github.com/hoover/docker-setup.git
  - cd docker-setup
  - mkdir -p volumes volumes/metrics volumes/metrics/users collections volumes/search-es-snapshots volumes/search-es/data
  - chmod 777 volumes/search-es-snapshots volumes/search-es/data
  - cp ../testsuite/docker-compose.travis.yml docker-compose.yml
  - cp ../testsuite/docker-compose.override.travis.yml docker-compose.override.yml
  - docker-compose up -d

- name: py.test
  image: docker/compose:1.24.0
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - cd docker-setup
  - docker-compose run --rm search bash -c '/wait && py.test --ignore=docker-setup -v'

services:
- name: docker daemon in docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
---
kind: pipeline
name: publish to docker hub

trigger:
  status:
  - success
  event:
  - push
  - tag

depends_on:
- test

steps:
- name: docker push branch ${DRONE_COMMIT_BRANCH}
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-search
    tags: ${DRONE_COMMIT_BRANCH}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
      excludes:
        - dependabot/*
    event:
    - push

- name: docker push autotag + latest
  image: plugins/docker
  settings:
    repo: liquidinvestigations/hoover-search
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: secret
name: docker_username
get:
  path: liquid/ci/drone.docker
  name: username

---
kind: secret
name: docker_password
get:
  path: liquid/ci/drone.docker
  name: password
