#!/usr/bin/env bash

set -e

COMMAND=$1
shift

case "$COMMAND" in

  'tests')
    export DJANGO_SETTINGS_MODULE=testsuite.settings
    exec py.test
    ;;

  'devserver')
    #@ localhost:8000
    set -x
    exec ./manage.py runserver "$@"
    ;;

  'server')
    #@ --host=0.0.0.0
    #@ --port=8080
    set -x
    exec waitress-serve "$@" hoover.wsgi:application
    ;;

  'worker')
    set -x
    exec ./manage.py worker "$@"
    ;;

  *)
    echo "Unknown command $COMMAND"
    ;;

esac
