#!/bin/bash -ex
cd "$(dirname ${BASH_SOURCE[0]})"

trap 'sudo rm -r docker-setup && rm .drone.yml.bak' EXIT

docker build . --tag liquidinvestigations/hoover-snoop2:$(git branch --show-current)
cp .drone.yml .drone.yml.bak
sed -i "s/py\.test --ignore=docker-setup -v/py\.test --ignore=docker-setup `echo $@`/g" .drone.yml.bak
drone exec --trusted --branch $(git branch --show-current) --event push --pipeline test .drone.yml.bak 