#!/bin/bash -ex

/wait

./manage.py migrate
./manage.py healthcheck
./manage.py synccollections "$SNOOP_COLLECTIONS"

if [[ "$DEBUG" == "true" ]]; then
	    # --max-requests 1 \  # poor man's autoreload
	  exec gunicorn --reload \
	    --access-logfile '-' \
	    --error-logfile '-' \
	    --log-level 'info' \
          --worker-class sync \
           --workers 4 \
           --threads 1 \
           --max-requests 1 \
           --keep-alive 60 \
           --timeout 600 \
 	 -b 0.0.0.0:8000 \
 hoover.site.wsgi:application
else
	exec gunicorn \
	    --error-logfile '-' \
          --worker-class sync \
           --workers 4 \
           --threads 1 \
           --max-requests 1 \
           --keep-alive 60 \
           --timeout 600 \
	 -b 0.0.0.0:8000 \
 hoover.site.wsgi:application
fi
