#!/bin/bash -ex

/wait

if [[ $NOMAD_ALLOC_INDEX  == "0" ]]; then
    (
        set +e
        while true; do
            sleep 60
            ./manage.py syncnextclouddirs
        done
    ) &
    (
        set +e
        while true; do
            sleep 3600
            ./manage.py purgenextclouddirs
        done
    ) &
fi

if [[ "$DEBUG" == "true" ]]; then
	    # --max-requests 1 \  # poor man's autoreload
	  exec gunicorn --reload \
             --preload \
	    --access-logfile '-' \
	    --error-logfile '-' \
	    --log-level 'info' \
           --worker-class $GUNICORN_WORKER_CLASS \
           --workers $GUNICORN_WORKERS \
           --threads $GUNICORN_THREADS \
           --max-requests $GUNICORN_MAX_REQUESTS \
           --keep-alive 120 \
           --timeout 600 \
           --graceful-timeout 300 \
 	 -b 0.0.0.0:8000 \
 hoover.site.wsgi:application
else
	exec gunicorn \
	    --error-logfile '-' \
           --worker-class $GUNICORN_WORKER_CLASS \
           --workers $GUNICORN_WORKERS \
           --threads $GUNICORN_THREADS \
           --max-requests $GUNICORN_MAX_REQUESTS \
           --keep-alive 120 \
           --timeout 600 \
           --graceful-timeout 300 \
	 -b 0.0.0.0:8000 \
 hoover.site.wsgi:application
fi
