# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('n', models.IntegerField(default=0)),
                ('expires', models.IntegerField()),
            ],
        ),
    ]
