# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20151125_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='slug',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='collection',
            name='loader',
            field=models.CharField(default='collector.loaders.collectible.Loader', max_length=2048),
        ),
        migrations.AlterField(
            model_name='collection',
            name='options',
            field=models.TextField(default='{}'),
        ),
    ]
