# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


def set_index(apps, schema_editor):
    if not hasattr(settings, 'ELASTICSEARCH_INDEX_PREFIX'):
        return
    Collection = apps.get_model('collector', 'Collection')
    for col in Collection.objects.all():
        col.index = settings.ELASTICSEARCH_INDEX_PREFIX + str(col.id)
        col.save()


def set_index_down(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20160211_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index',
            field=models.CharField(default='hoover', max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(set_index, set_index_down),
    ]
