# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0010_collection_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='loader',
            field=models.CharField(default='collector.loaders.upload.Loader', max_length=2048),
        ),
    ]
