# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_auto_20160815_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='users',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
