# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 09:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('index', models.CharField(max_length=256)),
                ('public', models.BooleanField(default=False)),
                ('loader', models.CharField(default='hoover.search.loaders.upload.Loader', max_length=2048)),
                ('options', models.TextField(default='{}')),
                ('users', models.ManyToManyField(blank=True, related_name='hoover_search_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
