# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-18 16:08
from __future__ import unicode_literals

from django.db import migrations
from urllib.parse import urlparse, urlunparse, ParseResult
from json import loads, dumps


def update_snoop_url(apps, schema_editor):
    Collection = apps.get_model('search', 'Collection')
    for collection in Collection.objects.all():
        options = loads(collection.options)
        if 'url' in options:
            url = urlparse(options['url'])
            new_url = ParseResult(url.scheme, url.netloc, '/collection/json', url.params,
                                  url.query, url.fragment)
            options['url'] = urlunparse(new_url)
            collection.options = dumps(options)
            collection.save()


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_collection_loader_state'),
    ]

    operations = [
        migrations.RunPython(update_snoop_url),
    ]
