# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_collection_loader_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='crawl_state',
            field=models.TextField(default='null'),
        ),
    ]
