# Generated by Django 2.2.7 on 2020-03-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_rename_user_hypens_to_dots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='loader',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='loader_state',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='options',
        ),
    ]
