# Generated by Django 3.1.3 on 2021-01-28 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hoover.search.models


def forwards(apps, schema_editor):
    from django.contrib.auth.models import User as ActualUser

    if schema_editor.connection.alias != 'default':
        return
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('search', 'Profile')
    for user in User.objects.all():
        # in historical model...
        # user.set_unusable_password()
        ActualUser.set_unusable_password(user)
        user.save()
        Profile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0006_auto_20200303_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=hoover.search.models.random_uuid, max_length=50)),
                ('preferences', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
