# Generated by Django 3.1.3 on 2021-10-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='avg_search_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='doc_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SearchResultCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField()),
                ('result', models.JSONField(default=None, null=True)),
                ('task_id', models.CharField(max_length=51)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('date_last_read', models.DateTimeField(auto_now_add=True)),
                ('collections', models.ManyToManyField(to='search.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
