# Generated by Django 3.1.3 on 2021-10-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20211004_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresultcache',
            name='task_id',
            field=models.CharField(max_length=51, unique=True),
        ),
    ]
