# Generated by Django 3.1.3 on 2021-10-22 06:41

from django.db import migrations, models
import hoover.search.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20211004_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresultcache',
            name='date_last_read',
        ),
        migrations.AlterField(
            model_name='searchresultcache',
            name='task_id',
            field=models.CharField(default=hoover.search.models.random_uuid, max_length=51, unique=True),
        ),
    ]
