# Generated by Django 3.1.3 on 2022-02-24 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0010_auto_20211022_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='uploaders',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='writeable',
            field=models.BooleanField(default=False),
        ),
    ]
