# Generated by Django 3.1.3 on 2022-11-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_batchresultcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='avg_batch_time',
            field=models.FloatField(default=0),
        ),
    ]
