# Generated by Django 3.1.3 on 2022-03-04 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0011_auto_20220224_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='uploaders',
        ),
        migrations.AddField(
            model_name='collection',
            name='uploader_groups',
            field=models.ManyToManyField(blank=True, related_name='hoover_search_upload_collections', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploader_users',
            field=models.ManyToManyField(blank=True, related_name='hoover_search_upload_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
