# Generated by Django 3.1.3 on 2022-12-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('search', '0013_uploads'), ('search', '0014_auto_20221214_1723')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('search', '0012_collection_avg_batch_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='writeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploader_groups',
            field=models.ManyToManyField(blank=True, related_name='hoover_search_upload_collections', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='collection',
            name='uploader_users',
            field=models.ManyToManyField(blank=True, related_name='hoover_search_upload_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('directory_id', models.IntegerField()),
                ('filename', models.CharField(max_length=256)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.collection')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload_id', models.UUIDField(null=True)),
                ('processed', models.BooleanField(default=False)),
                ('poll_task', models.CharField(max_length=64, null=True)),
                ('directory_path', models.CharField(max_length=256)),
                ('snoop_tasks_done', models.IntegerField(default=0)),
                ('snoop_tasks_total', models.IntegerField(default=0)),
            ],
        ),
    ]
