# Generated by Django 3.1.3 on 2023-02-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_uploads_squashed_0014_auto_20221214_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='index',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
