# Generated by Django 3.2.21 on 2024-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_uploads_squashed_0014_auto_20221214_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
