# Generated by Django 3.1.3 on 2023-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_nextcloudcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcloudcollection',
            name='name',
            field=models.CharField(default='test', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
