# Generated by Django 3.1.3 on 2023-02-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20230209_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
