# Generated by Django 3.1.3 on 2022-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_upload_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
