# Generated by Django 3.2.21 on 2024-02-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_nextcloudcollection_nextclouddirectory_webdavpassword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nextclouddirectory',
            options={'verbose_name_plural': 'Nextcloud directories'},
        ),
        migrations.AddField(
            model_name='nextclouddirectory',
            name='deleted_from_nextcloud',
            field=models.DateTimeField(null=True),
        ),
    ]
