# Generated by Django 3.1.3 on 2022-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_upload_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='poll_task',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
