# Generated by Django 3.2.21 on 2024-02-08 14:15

from django.db import migrations, models


def set_default_name(apps, _):
    NextcloudCollection = apps.get_model('search', 'NextcloudCollection')
    for obj in NextcloudCollection.objects.all():
        obj.name = obj.directory.name
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20240202_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcloudcollection',
            name='name',
            field=models.CharField(default='x', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_name),
    ]
