# Generated by Django 3.2.21 on 2024-02-09 15:41

from django.db import migrations, models
import hoover.search.validators


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_nextcloudcollection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='name',
            field=models.CharField(max_length=256, unique=True, validators=[hoover.search.validators.validate_collection_name]),
        ),
    ]
