# Generated by Django 3.1.3 on 2022-12-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_upload_directory_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='snoop_tasks_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload',
            name='snoop_tasks_total',
            field=models.IntegerField(default=0),
        ),
    ]
