# Generated by Django 3.2.21 on 2024-02-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_alter_nextcloudcollection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcloudcollection',
            name='collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.collection'),
            preserve_default=False,
        ),
    ]
