# Generated by Django 3.2.21 on 2023-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_auto_20231115_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='default_table_header',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='ocr_languages',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='s3_blobs_access_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='s3_blobs_address',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='s3_blobs_secret_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
