# Generated by Django 3.2.21 on 2024-02-15 15:57

from django.db import migrations, models
import django.db.models.deletion
import hoover.search.validators


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_nextcloudcollection_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextcloudcollection',
            name='directory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.nextclouddirectory', validators=[hoover.search.validators.validate_directory_path]),
        ),
    ]
